### ISSUE TITLE
Adicionar breadcrumbs nas páginas do curso

### ISSUE THREAD

**Issue by james-sabel** [james-sabel/tw-livre#2]
A inclusão de breadcrumbs nas páginas do curso tornaria a navegação melhor em termos de usabilidade.

O ideal é usar algum recurso do Jekyll para que os breadcrumbs sejam gerados automaticamente, evitando a necessidade de mantê-los manualmente.

**Comment by MichelleMello** [comment]
Oi, James! Tudo bem? Tava vendo as issues desse repositório e posso contribuir adicionando os breadcrumbs ao código. Posso ajudar nisso?

**Comment by james-sabel** [comment]
@MichelleMello Muuuuuito obrigado, ficou demais! Mandei uma pequena revisão lá no PR. É só um detalhe que faltou adicionar, daí com isso a gente já finaliza! :100:

**Comment by james-sabel** [comment]
Resolvido pelo PR #11 

Obrigado, @MichelleMello :heart:
